name: 'Codez Action'
description: 'Codex in GitHub Actions'
author: 'yiweishen'
branding:
  icon: 'code'
  color: 'purple'

inputs:
  github-token:
    description: 'Specify the GitHub Token'
    required: true
  event-path:
    description: 'Specify the path to the GitHub Event JSON file'
    default: ${{ github.event_path }}
    required: false
  timeout:
    description: 'Specify timeout duration (seconds)'
    default: '600'
    required: false
  openai-api-key:
    description: 'Specify the OpenAI API Key'
    required: true
  openai-base-url:
    description: 'Specify the OpenAI API base URL'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile.github_action_dockerhub'
