name: 'Codez Action'
description: 'Codex in GitHub Actions'
author: 'yiweishen'
branding:
  icon: 'code'
  color: 'purple'

inputs:
  github-token:
    description: 'Specify the GitHub Token'
    required: true
  event-path:
    description: 'Specify the path to the GitHub Event JSON file'
    default: ${{ github.event_path }}
    required: false
  timeout:
    description: 'Specify timeout duration in seconds (must be a positive integer)'
    default: '600'
    required: false
  openai-api-key:
    description: 'Specify the OpenAI API Key'
    required: true
  openai-base-url:
    description: 'Specify the OpenAI API base URL'
    required: false
  direct-prompt:
    description: 'One-shot prompt for automated workflows. Bypasses comment triggers.'
    required: false
  trigger-phrase:
    description: 'Custom trigger phrase to invoke Codez (default: /codex)'
    required: false
    default: '/codex'
  assignee-trigger:
    description: 'Comma-separated list of GitHub usernames. Codez will run when an issue is assigned to these users.'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'docker://ghcr.io/yiweishen/codez:latest'
