name: 'Codez Action'
description: 'Codex in GitHub Actions'
author: 'yiweishen'
branding:
  icon: 'code'
  color: 'purple'

inputs:
  github-token:
    description: 'Specify the GitHub Token'
    required: true
  event-path:
    description: 'Specify the path to the GitHub Event JSON file'
    default: ${{ github.event_path }}
    required: false
  timeout:
    description: 'Specify timeout duration in seconds (must be a positive integer)'
    default: '600'
    required: false
  openai-api-key:
    description: 'Specify the OpenAI API Key'
    required: true
  openai-base-url:
    description: 'Specify the OpenAI API base URL'
    required: false
  openai-model:
    description: 'OpenAI model identifier to use (default: gpt-5.1-codex-mini)'
    required: false
  direct-prompt:
    description: 'One-shot prompt for automated workflows. Bypasses comment triggers.'
    required: false
  trigger-phrase:
    description: 'Custom trigger phrase to invoke Codez (default: /codex)'
    required: false
    default: '/codex'
  assignee-trigger:
    description: 'Comma-separated list of GitHub usernames. Codez will run when an issue is assigned to these users.'
    required: false
    default: ''
  codex-env:
    description: |
      Custom environment variables to inject into the Codex CLI execution context.
      Accepts either a YAML mapping (multiline) or comma-separated key=value pairs.
    required: false
    default: ''
  images:
    description: |
      Comma-separated or newline-separated list of local image file paths to include in the Codex CLI invocation.
      Each image can be referenced in the prompt by `<image_0>`, `<image_1>`, etc.
    required: false
    default: ''
  fetch:
    description: 'Fetch known URLs referenced in the prompt and include their contents in the prompt'
    required: false
    default: 'false'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/yiweishen/codez:latest'
