const LOADING_PHRASES: string[] = [
  'Decrypting punchlines with 256-bit humor...',
  'Loading… the progress bar is in another castle.',
  'Rebooting the joke processor… please laugh responsibly.',
  'Running sudo make funny... permission denied.',
  'Our AI is training… but it skipped leg day.',
  'Waiting for Stack Overflow to answer...',
  'Optimizing code... by adding more comments and fewer bugs.',
  'Compiling jokes... expect a few warnings.',
  'Spinning up containers of laughter...',
  'Oops, we accidentally opened a portal to production.',
  'Swapping memory... now where did I put that pun?',
  'Trying to center a div... wish us luck.',
  'Running npm install funny... 542 dependencies later...',
  'Searching for a semicolon in a haystack...',
  'Connecting to Wi-Funny network...',
  'Loading logic... please ignore the null pointer.',
  'Installing humor patch v1.0.7 — now with 17% more sarcasm.',
  'Oops! Kernel panic... just kidding, it’s a loading joke.',
  'Scanning for missing closing tags...',
  'Running unit tests on this joke... all passed except QA.',
  'Re-indexing punchlines...',
  'Deploying bad puns to the frontend...',
  '404: Witty remark not found — please wait...',
  'Trying to resolve circular dependencies... in the joke structure.',
  'Generating randomness... humor included by chance.',
  'Connecting to GitHub... and blaming someone else.',
  'Starting the infinite loop of comedy...',
  "Authenticating puns... password: 'whythelongload'",
  'Parsing sarcasm syntax... brace yourself.',
  'Cleaning up code... and sweeping bugs under the rug.',
  'Procrastinating algorithms... deadlines apply.',
  'Refactoring spaghetti code... sauce is everywhere.',
  'Herding cats... errors are on the loose.',
  'Inserting TODO comments... forever.',
  'Waiting for the CI pipeline to finish... coffee break!',
  'Feeding caffeine to the compiler... energizing binaries.',
  'Waking up modules... snooze button pressed.',
  'Buffering witty comebacks... please hold.',
  'Compiling with optimism... warnings: 42.',
  'Overflowing stack... recursive puns ahead.',
  'Debugging in production... wish me luck.',
  'Applying hotfix... life support engaged.',
  'Charging developer batteries... 0% → 100%.',
  'Writing unit tests for these jokes... assertions pending.',
  'Linting code... your style is my command.',
  'Upgrading dependencies... hope for no breaking changes.',
  'Validating JSON... with human emotions.',
  'Polyfilling promises... callbacks are jealous.',
  'Downloading a world of bugs... network unstable.',
  'Loading virtual machines... reality optional.',
  'In npm we trust... sometimes.',
  'Escaping the infinite loop... almost there.',
  'Encrypting developer secrets... shh!',
  'Sassying style sheets... CSS making sass happen.',
  'Partitioning hard drives... making room for humor.',
  'Protecting production servers... hairdryer mode on.',
  'Preheating IDE... syntax highlighting incoming.',
  'Unlocking debugger... breakpoints engaged.',
  'Wiping clipboard history... secrets safe.',
  'Loading README changes... hope you read this.',
];

export default LOADING_PHRASES;
